---
- name: create inventory file
  hosts: all
  tasks:
    - name: set db host_type
      shell: 'ls /etc/my.cnf'
      register: result_db
      ignore_errors: true
    - name: set db variable
      set_fact:
        hostname: "{{ ansible_hostname }}"
        db_group: "{{ '1' if (result_db.rc == 0) else '0' }}"

    - name: set was host_type
#      shell: 'ps aux| grep java | grep -v grep'
      shell: 'ls /var/www/html/index.html'
      register: result_was
      ignore_errors: true
    - name: set variable
      set_fact:
        hostname: "{{ ansible_hostname }}"
        was_group: "{{ '1' if (result_was.rc == 0) else '0' }}"

    - name: set web host_type
      shell: 'ps aux | grep httpd | grep -v grep'
      register: result_web
      ignore_errors: true
    - name: set variable
      set_fact:
        hostname: "{{ ansible_hostname }}"
        web_group: "{{ '1' if (result_web.rc == 0) else '0' }}"

    - name: create txt from template
      template:
        src: inv.j2
        dest: inv.txt
      delegate_to: localhost
  
